import = ["$HOME/dotfiles/alacritty/dracula.toml"]

[colors.vi_mode_cursor]
#cursor = "CellForeground"
#text = "CellBackground"

[font]
#builtin_box_drawing = true
size = 13

[font.bold]
style = "Bold"

[font.normal]
family = "IosevkaTermNerdFontPropo"
#family = "MesloLGSNerdFont"
#family = "FiraCodeNerdFont"
style = "SemiBold"
