import = ["$HOME/dotfiles/alacritty/dracula.toml"]

[colors.vi_mode_cursor]
#cursor = "CellForeground"
#text = "CellBackground"

[font]
builtin_box_drawing = true
size = 13

[font.bold]
style = "Heavy"

[font.normal]
#family = "IosevkaTermNerdFont"
family = "IosevkaTerm Nerd Font Propo"
#family = "MesloLGSNerdFont"
#family = "FiraCodeNerdFont"
style = "SemiBold"

[[keyboard.bindings]]
key = "F"
mods = "Alt"
action = "ToggleFullscreen"
