set-option -sa terminal-overrides ",xterm*:Tc"
set -s escape-time 0

# enable mouse in tmux
set -g mouse on 

# prefix key bindings
set -g prefix C-Space
bind C-Space send-prefix

# Shift Alt vim keys to switch window
bind -n M-H previous-window
bind -n M-L next-window

# split window
bind v split-window -v -c "#{pane_current_path}"
bind h split-window -h -c "#{pane_current_path}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dracula/tmux' # theme

# dracula theme settings
set -g @dracula-show-flags true 
set -g @dracula-show-empty-plugins false 
set -g @dracula-plugins "cpu-usage ram-usage tmux-ram-usage network battery time"
# battery label
set -g @dracula-battery-label false
set -g @dracula-show-battery-status true
set -g @dracula-show-powerline true 
set -g @dracula-no-battery-label false 
# network
set -g @dracula-network-ethernet-label "󰒪"
set -g @dracula-network-offline-label "󰖪 Offline"
set -g @dracula-network-wifi-label " "
set -g @dracula-network-colors "light_purple dark_gray"
# weather
set -g @dracula-show-fahrenheit false
set -g @dracula-fixed-location "31.157,121.424"
set -g @dracula-weather-options "force-fetch"
set -g @dracula-show-timezone false
set -g @dracula-time-format "%a %F %R"
# set -g @dracula-git-disable-status true
# END of dracula theme settings

# set -g @plugin 'tmux-plugins/tmux-yank' # system clipboard


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# test message
